spring.application.name=Cliente
spring.main.web-application-type=none
cliente.ui.enabled=true

client.network.tcp-timeout-ms=5000
client.network.udp-timeout-ms=5000
client.transfer.max-parallel-uploads=4

spring.datasource.url=jdbc:h2:file:./data/clientedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
